# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for LLM Chat App
# One can use this file to customize the build process, such as adding data files, hidden imports, etc. 
# One_file can be used to create a single executable file, but it may increase the build time and the size of the executable.   

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('resources/', 'resources'),
        ('ui_designer/', 'ui_designer'),
        ('extension/', 'extension'),
        ('README.md', '.'),           
        ('LICENSE', '.'),        
        ('API_SERVER.md', '.'),
        ('IDE_INTEGRATION.md', '.'),
    ],
    hiddenimports=[
        'flask',
        'werkzeug',
        'werkzeug.serving',
        'openai',
        'markdown',
        'certifi',
        'urllib3',
        'charset_normalizer',
        'PySide6.QtCore',
        'PySide6.QtWidgets',
        'PySide6.QtGui',
        'PySide6.QtUiTools',
        'sqlite3',
        'pysqlite2',
        'queue',
        'threading',
        'time',
        'json',
        'base64',
        'socket',
        'pathlib',
        're',
        'datetime',
        'importlib.metadata',
        'importlib.resources',
        'markdown.extensions.extra',
        'markdown.extensions.fenced_code',
        'markdown.extensions.codehilite',
        'logging',
        'webbrowser',
        'shutil',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PyQt5',
        'PyQt6',
        'tkinter',
        '_tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'IPython',
        'jupyter',
        'notebook',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name='LLM Chat App',
    debug=False,
    strip=False,
    upx=True,
    console=False,
    icon='resources/app_icon.ico',
)