# utils/constants.py
# This file contains constant values used throughout the LLM Chat App.

APP_NAME = "LLM Chat App"
APP_VERSION = "4.0.0"
APP_AUTHOR = "Arean Narrayan"

DEFAULT_MODEL = "meta/llama-3.3-70b-instruct"
DEFAULT_TEMPERATURE = 0.7
DEFAULT_MAX_TOKENS = 4096
DEFAULT_TIMEOUT = 60

NVIDIA_BASE_URL = "https://integrate.api.nvidia.com/v1"

# Connection settings
CONNECTION_CHECK_INTERVAL_CONNECTED_MS = 10000
CONNECTION_CHECK_INTERVAL_DISCONNECTED_MS = 3000
CONNECTION_TIMEOUT_SECONDS = 1

# API settings
DEFAULT_MAX_TOKENS = 4096
DEFAULT_TEMPERATURE = 0.7
API_TIMEOUT_SECONDS = 60
RATE_LIMIT_REQUESTS = 40
RATE_LIMIT_WINDOW_SECONDS = 60

# Chat settings
RESPONSE_BUFFER_CHARS = 64000
TYPING_INDICATOR_TEXT = "🤖 Assistant is typing..."